server.port=3000
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=kubraeser
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=nEsARu/pG2RX3/aU9CMmvrlOGgKpYuQmYU2g0GiqSEQ=